apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetrygen
  namespace: monitoring
  labels: { app: telemetrygen }
spec:
  replicas: 1
  selector:
    matchLabels: { app: telemetrygen }
  template:
    metadata:
      labels: { app: telemetrygen }
    spec:
      containers:
        - name: telemetrygen
          image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:latest
          args:
            - metrics
            - --otlp-endpoint=otel-collector:4317
            - --otlp-insecure
            - --duration=8760h
            - --rate=10
            - --batch-size=10
          resources:
            requests: { cpu: 20m, memory: 32Mi }
            limits: { memory: 64Mi }
