prometheus:
  prometheusSpec:
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    retention: 6h
    resources:
      requests: { cpu: 100m, memory: 400Mi }
      limits:   { memory: 800Mi }

grafana:
  adminPassword: admin
  defaultDashboardsTimezone: Asia/Bangkok
  resources:
    requests: { cpu: 50m, memory: 192Mi }
    limits:   { memory: 512Mi }

alertmanager:
  alertmanagerSpec:
    resources:
      requests: { cpu: 25m, memory: 64Mi }
      limits:   { memory: 128Mi }

prometheusOperator:
  resources:
    requests: { cpu: 50m, memory: 128Mi }
    limits:   { memory: 256Mi }
