apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: waves-demo
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 2
  selector:
    matchLabels: { app: backend }
  template:
    metadata:
      labels: { app: backend }
    spec:
      containers:
        - name: backend
          image: hashicorp/http-echo:0.2.3
          args:
            - "-listen=:5678"
            - "-text=hello from backend"
          ports:
            - containerPort: 5678
          resources:
            requests: { cpu: 20m, memory: 16Mi }
            limits: { cpu: 100m, memory: 32Mi }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: waves-demo
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: 2
  selector:
    matchLabels: { app: frontend }
  template:
    metadata:
      labels: { app: frontend }
    spec:
      containers:
        - name: frontend
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: frontend-content
              mountPath: /usr/share/nginx/html
            - name: frontend-nginx
              mountPath: /etc/nginx/conf.d
          resources:
            requests: { cpu: 20m, memory: 16Mi }
            limits: { cpu: 100m, memory: 32Mi }
      volumes:
        - name: frontend-content
          configMap:
            name: frontend-content
        - name: frontend-nginx
          configMap:
            name: frontend-nginx
